using System.ComponentModel.DataAnnotations;
using StabilityMatrix.Core.Attributes;
using StabilityMatrix.Core.Models.Api.Comfy.Nodes;

namespace StabilityMatrix.Core.Models.Api.Comfy.NodeTypes;

/// <summary>
/// Comfy SaveAnimatedMP4Advanced node for exporting video with full MP4 encoding control.
/// 
/// This is an advanced custom node that supports:
/// - CRF (Constant Rate Factor) for quality control
/// - Codec selection (libx264 or libx265)
/// - Container format (mp4 or mkv)
/// - Bitrate configuration
/// - Advanced filename generation with model/seed/sampler info
/// 
/// Node Source: StabilityMatrix/custom_nodes/save_animated_mp4_advanced.py
/// 
/// This node requires:
/// - FFmpeg installed and in PATH
/// - ComfyUI with the custom node loaded
/// </summary>
[TypedNodeOptions(Name = "SaveAnimatedMP4Advanced")]
public record SaveAnimatedMP4Advanced : ComfyTypedNodeBase
{
    /// <summary>
    /// Input images for export.
    /// Must be ImageNodeConnection to properly reference the image source node.
    /// Expected shape: (frames, height, width, channels)
    /// </summary>
    public required ImageNodeConnection Images { get; init; }

    /// <summary>
    /// Frames per second (1-120)
    /// Typical values: 24 (cinema), 30 (broadcast), 60 (high fps)
    /// </summary>
    [Range(1.0, 120.0)]
    public required double Fps { get; init; }

    /// <summary>
    /// Output filename prefix (without extension)
    /// Example: "InferenceVideo" → "InferenceVideo_[pid].mp4"
    /// The actual filename is generated by FFmpeg with process ID suffix
    /// </summary>
    public required string FilenamePrefix { get; init; }

    /// <summary>
    /// Constant Rate Factor - compression quality (0-51)
    /// Lower values = better quality
    /// 
    /// Recommended values:
    /// - 0: Lossless (largest file)
    /// - 18: Default (good quality, reasonable file size)
    /// - 23: Standard quality
    /// - 28: Smaller file, acceptable quality
    /// - 51: Lowest quality (smallest file)
    /// </summary>
    [Range(0, 51)]
    public required int Crf { get; init; }

    /// <summary>
    /// Video codec for encoding
    /// Options: "libx264" (H.264) or "libx265" (H.265/HEVC)
    /// 
    /// H.264 (libx264):
    /// - More compatible (older devices)
    /// - Faster to encode
    /// - Larger files
    /// - Better for streaming
    /// 
    /// H.265 (libx265):
    /// - Better compression (~50% smaller than H.264)
    /// - Slower to encode (2-10x slower)
    /// - Less widely supported
    /// - Better for archiving
    /// </summary>
    public required string Codec { get; init; }

    /// <summary>
    /// Container format for the video
    /// Options: "mp4" or "mkv"
    /// 
    /// MP4:
    /// - Standard format
    /// - Excellent compatibility
    /// - Optimized for streaming
    /// 
    /// MKV (Matroska):
    /// - More flexible
    /// - Better for archiving
    /// - Less widely supported
    /// - Can store more metadata
    /// </summary>
    public required string Container { get; init; }

    /// <summary>
    /// Target bitrate in kilobits per second (500-50000)
    /// 
    /// Note: CRF (quality-based) encoding is generally preferred over bitrate.
    /// If both CRF and bitrate are specified, CRF typically takes precedence.
    /// 
    /// Typical bitrate values:
    /// - 500-2000 kbps: Web streaming (low quality, small size)
    /// - 2000-5000 kbps: Streaming with better quality
    /// - 5000-10000 kbps: High quality
    /// - 10000+ kbps: Archive/Master quality
    /// </summary>
    [Range(500, 50000)]
    public required int Bitrate { get; init; }

    // ========== HIDDEN INPUTS - Used for advanced filename generation ==========
    
    /// <summary>
    /// Model name (e.g., "sd15", "sdxl", "pony")
    /// Used for filename generation
    /// </summary>
    public string ModelName { get; init; } = "";

    /// <summary>
    /// Model file path
    /// Used for filename generation to extract model name if ModelName is empty
    /// </summary>
    public string ModelPath { get; init; } = "";

    /// <summary>
    /// Generation seed
    /// Used for filename generation
    /// </summary>
    public int Seed { get; init; } = -1;

    /// <summary>
    /// Sampler name (e.g., "DPM++", "Euler", "Heun")
    /// Used for filename generation
    /// </summary>
    public string SamplerName { get; init; } = "";

    /// <summary>
    /// Scheduler name (e.g., "karras", "simple")
    /// Used for filename generation
    /// </summary>
    public string SchedulerName { get; init; } = "";

    /// <summary>
    /// CFG Scale value
    /// Used for filename generation
    /// </summary>
    public double Cfg { get; init; } = 0.0;

    /// <summary>
    /// Number of sampling steps
    /// Used for filename generation
    /// </summary>
    public int Steps { get; init; } = 0;

    /// <summary>
    /// VAE name
    /// Used for filename generation
    /// </summary>
    public string VaeName { get; init; } = "";
}
